Делает оставшиеся элементы
htmlacademy-htmlcss/283545-sedona-32 pull request #11
Opened 2021-11-13 17:53 UTC by Haarkin

Чекбоксы пропали и непонятная ситуация с инпутами у ползунка

2021-11-13 17:55 UTC, Haarkin commented on catalog.html
> +                     <input class="catalog-filter-input" type="number" name="min-price" placeholder="0"> от
Нужно нормально рассмотреть на консультации

2021-11-13 21:18 UTC, wrgraff requested changes

2021-11-13 21:18 UTC, wrgraff commented on css/styles.css
> +  padding-left: 36px;
После перехода на Грид этот отступ мешает, смещая все элементы вправо

2021-11-13 21:18 UTC, wrgraff commented on css/styles.css
> +  background-image: url('../images/icons/checked-checkbox.svg');
Картинка должна быть только у чекбокса, надо или ему задать ее, или сбросить в radio-инпуте

2021-11-13 21:18 UTC, wrgraff commented on css/styles.css
> +.control-input:checked + .control-lable::after {
Не хватает скругления чекбоксам

2021-11-13 21:18 UTC, wrgraff commented on css/styles.css
> +  font-size: 400;
Это `font-size` или `font-weight`?

2021-11-13 21:18 UTC, wrgraff commented on css/styles.css
> +  outline: rgba(255, 255, 255, 1);
Зачем в аутлайне при статичном состоянии задан только цвет?

2021-11-13 21:18 UTC, wrgraff commented on css/styles.css
> +.range-toggle:active,
А для `:active` зачем это задавать вместе с фокусом?

2021-11-13 21:18 UTC, wrgraff commented on css/styles.css
> +  font-size: 400;
Здесь тоже то ли размер, то ли вес

2021-11-13 21:18 UTC, wrgraff commented on css/styles.css
> +.control:focus .control-lable::before {
Элемент `.control` — это лейбл, он не может быть в фокусе, поэтому фокусировка не работает.
В фокусе должен быть именно инпут.

2021-11-13 21:18 UTC, wrgraff commented on css/styles.css
> +.control-lable::before {
Конечно, все классы надо поправить:
```suggestion
.control-label::before {
```

2021-11-13 21:18 UTC, wrgraff commented on catalog.html
> +                     <input class="catalog-filter-input" type="number" name="min-price" placeholder="0"> от
Сделал [про инпуты обзорный видос ](https://youtu.be/pNEsIIvI7mw)(не инструкцию, именно обзор).
Хорошо бы посмотреть его успеть до консультации

2021-11-13 21:21 UTC, wrgraff commented
И есть еще [про настройку фокусов](https://youtu.be/hGnlJQKQJ7Q), тоже не помешает

2021-11-14 20:14 UTC, wrgraff requested changes

2021-11-14 20:14 UTC, wrgraff commented on catalog.html
> +  <div class="modal-dissable">
Класс не оч понятный на самом деле.
Вроде как пишется `disable`, ну и в принципе можно было бы ограничиться вообще обычным `modal`, а то, что оно скрыто по умолчанию понятно уже из того, что оно — модалка

2021-11-14 20:14 UTC, wrgraff commented on catalog.html
> +          </section>
А для чего один единственный заголовок заключен в `<section>`?
Тогда уж им должно быть размечено все модальное окно

2021-11-14 20:14 UTC, wrgraff commented on catalog.html
> +          </p>
Для детей и взрослых отдельными кнопками придется разметить "+" и "-":
![изображение](https://user-images.githubusercontent.com/37917037/141696832-34731faf-7826-4ace-a0fe-b529f44831aa.png)

2021-11-14 20:14 UTC, wrgraff commented on catalog.html
> +        <div class="modal-register-form">
А где сама `<form>`?

2021-11-14 20:14 UTC, wrgraff commented on catalog.html
> +        </div>
А где кнопка отправки формы?

2021-11-14 20:14 UTC, wrgraff commented on css/styles.css
> +  right: 426px;
Модальные окна должны ровно по центру позициронироваться.
А попап — к месту, где вызван. У тебя тут ни то, ни другое

2021-11-14 20:14 UTC, wrgraff commented on css/styles.css
> +  box-shadow: 0px 25px 50px rgba(0, 0, 0, 0.15);
```suggestion
  box-shadow: 0 25px 50px rgba(0, 0, 0, 0.15);
```

2021-11-14 20:14 UTC, wrgraff commented on css/styles.css
> +  outline: 1px solid #E6E6E6;
Оставь `outline` на фокусы, изначально видимые рамки рисуются бордером

2021-11-16 16:27 UTC, merged

2021-11-16 16:28 UTC, wrgraff commented
Еще очень много правок, особенно на странице каталога.
Старайся идти сверху вниз, чем точнее будет совпадение сверху, тем проще подгонять и дальше внизу.