Сетка страницы и крупных блоков на флексах для главной страницы
htmlacademy-htmlcss/283545-sedona-32 pull request #5
Opened 2021-10-28 20:00 UTC by Haarkin

---
:mortar_board: [Сетка страницы и крупных блоков на флексах для главной страницы](https://up.htmlacademy.ru/htmlcss/32/user/283545/tasks/7)

:boom: https://htmlacademy-htmlcss.github.io/283545-sedona-32/5/

2021-10-29 20:00 UTC, wrgraff requested changes
Это не стандартное, а видео-ревью. Комментарии не очень подробные, так как я разобрал подробно в записи.
Смотри [запись ревью](https://youtu.be/geM16bgcg0Y), а на комментарии просто ориентируйся, чтобы отслеживать что поправил.

2021-10-31 12:08 UTC, wrgraff requested changes

2021-10-31 12:08 UTC, wrgraff commented on css/styles.css
> +    flex-grow: 1;
Без ширины центральный элемент не встанет по центру

2021-10-31 12:08 UTC, wrgraff commented on css/styles.css
> +  }
А если появится 6-й, 7-й и 8-й элемент?

Логичнее было бы задать `.advantages-item` ширину 400 пикселей, а большим пунктам — полную ширину.

2021-10-31 12:08 UTC, wrgraff commented on index.html
> +    <div class="background-container">
Форматирование не только не поправил, но и добавил ошибок.
Это нарушение базового критерия [PROJ-01](https://up.htmlacademy.ru/htmlcss/32/criteries#PROJ-01), поправить и затем поддерживать нужно _обязательно_

2021-10-31 18:30 UTC, Haarkin commented on css/styles.css
> +    flex-grow: 1;
Там наверху width указан

2021-10-31 19:15 UTC, merged